apiVersion: v1
kind: Secret
metadata:
  name: choretrack-db-secret
  namespace: choretrack
type: Opaque
stringData:
  primary-url: "Host=choretrack-pgbouncer;Port=5432;Database=choretrack_db;Username=postgres;Password=CHANGE_ME;Pooling=true;Minimum Pool Size=2;Maximum Pool Size=20;No Reset On Close=true"
  replica-url: "Host=choretrack-pgbouncer-replica;Port=5432;Database=choretrack_db;Username=postgres;Password=CHANGE_ME;Pooling=true;Minimum Pool Size=2;Maximum Pool Size=20;No Reset On Close=true"
  replicator-password: "CHANGE_ME"
  postgres-password: "CHANGE_ME"
